ARENA_WIDTH = 670
ARENA_HEIGHT = 846
ARENA_OFFSET_X = 670/2

BLOB_RADII = [
    22.5,
    30,
    41,
    47,
    61,
    79,
    90,
    109.5,
    123,
    152.5,
    180,
]

ACTUAL_ARENA_SIZE = (ARENA_WIDTH, (ARENA_HEIGHT + 2*max(BLOB_RADII)))
ACTUAL_ASPECT_RATIO = ACTUAL_ARENA_SIZE[0] / ACTUAL_ARENA_SIZE[1]

NN_VIEW_WIDTH = 40
NN_VIEW_HEIGHT = int(NN_VIEW_WIDTH / ACTUAL_ASPECT_RATIO)

NEXT_BLOB_HEIGHT = max(BLOB_RADII)
NN_NEXT_BLOB_HEIGHT = int(NEXT_BLOB_HEIGHT / (ACTUAL_ARENA_SIZE[1] / NN_VIEW_HEIGHT))

BLOB_COLORS = [(x, x, x) for x in range(0, 255, 255//len(BLOB_RADII))]